# Raspberry Pi OS "Bookworm" First-Boot Configuration
# This file is ONLY used to get the device onto the network.
# All other kiosk configuration is handled by kioskbrowser.ini.

config_version = 1

[wlan]
ssid = "YOUR_WIFI_SSID"
password = "YOUR_WIFI_PASSWORD"
password_encrypted = false
country = "US"